### ISSUE TITLE
Feature request: Group content by key

### ISSUE THREAD

**Issue by 3r4i** [rasyidf/UFA.Localization#1]
First of all, thank you for providing such a useful tool for WPF localization.

But I am missing a important feature: Is there any way to group the content of the language pack (in my case json) by the key?

Thank you in advance.

## Expected Behavior
```
{
     "Languages": [
        {
	   "EnglishName": "English",
           "CultureName": "English - United States",
           "Culture": "en-US"
        },
        {
	   "EnglishName": "Indonesian",
           "CultureName": "Bahasa Indonesia",
           "Culture": "id-ID"
        }
    ],
    "Data": [ 
    	{ 
	  "Id": 0, 
	  "Language": {
	    "English": "Window Title",
	    "Indonesian": "Judul Jendela"
	  }
    	},
	{ 
	  "Id": 11, 
	  "Language": {
	    "English": "File",
	    "Indonesian": "Berkas"
	  }
    	}
    ]

}
```

## Current Behavior
```
{
    "EnglishName": "Indonesian", "CultureName": "Bahasa Indonesia",
    "Culture": "id-ID",
    "Data": [ 
    	{ "Id": 0, "Header": "Judul Jendela" }, 
    	{ "Id": 11, "Header": "Berkas" }
    ]
}
```

**Comment by rasyidf** [comment]
Thank you for using this, and of course your suggestion.
currently it isn't possible to do that, but single package for language maybe good approach as if it's just supporting some language.

I'll try to implement that as soon as possible.

**Comment by rasyidf** [comment]
Thanks to you, i've found some structural error after playing with multiple language at same file.
