### ISSUE TITLE
Can't build due to code signing

### ISSUE THREAD

**Issue by SKProCH** [rasyidf/UFA.Localization#5]
`Microsoft.Common.CurrentVersion.targets (3222, 5): [MSB3322] Failed to get MD5 checksum for key file" rasyidf.pfx ". File 'C:\Users\SKProCH\RiderProjects\Rasyidf.Localization\Localization\rasyidf.pfx' not found.`

## Possible Solution

Disable code signing

## Steps to Reproduce (for bugs)

1. Clone repository
2. Try to build

**Comment by rasyidf** [comment]
I've removed the code signing, fixed. :)
