### ISSUE TITLE
Demo app don't work

### ISSUE THREAD

**Issue by SKProCH** [rasyidf/UFA.Localization#6]
Error starting work due to attempt to load languages

## Steps to Reproduce (for bugs)

1. Clone repo
2. Fix #5 
3. Build demo
4. Try to run demo

## Your Environment

* Version used: last
* NET Framework : 4.8
* Operating System and version (desktop or mobile): Win 10

**Comment by rasyidf** [comment]
There are a several bugs that occur after version 0.5.1, fixed now.
